source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "7.0"

target "XuexiBaoFramework" do

pod 'AFNetworking', '~> 2.4.1'
#pod 'AFNetworking', :path => '/Users/kimziv/Documents/mywork/question_edu_iphone/Project/education/Specs'
#pod 'AFNetworking', :git => 'https://github.com/AFNetworking/AFNetworking.git', :tag => '2.0.3'
#pod 'AFNetworking', :git => 'https://github.com/AFNetworking/AFNetworking.git', :commit => '5266874bcc79c1afa627e590f982e50f6886f25f'

pod 'MagicalRecord', :git => 'https://github.com/magicalpanda/MagicalRecord.git', :commit => '11e1dcdeb78261ae6b02304707d5220dc0cf95e8'

pod 'Cordova',  '~> 3.8.0'
pod 'pop', '~> 1.0'


#pod 'Reachability', '~> 3.1.0'
#pod 'INTULocationManager', '~> 1.1.0'

end

#xcodeproj 'education/education.xcodeproj'
