# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'xcomet' do
pod 'CocoaLumberjack'
pod 'GCNetworkReachability', '~> 1.3.2'
end

target 'xcometTests' do

end

